In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = load_breast_cancer()

In [3]:
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target

df.sample(4)

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
143        12.90         15.92           83.74      512.2          0.08677   
509        15.46         23.95          103.80      731.3          0.11830   
556        10.16         19.59           64.73      311.7          0.10030   
437        14.04         15.98           89.78      611.2          0.08458   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
143           0.09509        0.048940              0.03088         0.1778   
509           0.18700        0.203000              0.08520         0.1807   
556           0.07504        0.005025              0.01116         0.1791   
437           0.05895        0.035340              0.02944         0.1714   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
143                 0.06235  ...          21.82            97.17       643.8   
509                 0.07083  ...          36.33           117.70       909.4   
556                 0.06331  ...          22.88            67.88       347.3   
437                 0.05898  ...          21.58           101.20       750.0   

     worst smoothness  worst compactness  worst concavity  \
143            0.1312             0.2548          0.20900   
509            0.1732             0.4967          0.59110   
556            0.1265             0.1200          0.01005   
437            0.1195             0.1252          0.11170   

     worst concave points  worst symmetry  worst fractal dimension  target  
143               0.10120          0.3549                  0.08118       1  
509               0.21630          0.3013                  0.10670       0  
556               0.02232          0.2262                  0.06742       1  
437               0.07453          0.2725                  0.07234       1  

[4 rows x 31 columns]

In [4]:
df.shape

(569, 31)

In [5]:
sample_1 = df.sample(200, replace = True)
sample_2 = df.sample(200, replace = True)
sample_3 = df.sample(200, replace = True)

In [6]:
sample_1.shape

(200, 31)

In [7]:
from sklearn.tree import DecisionTreeClassifier

In [8]:
base_model_1 = DecisionTreeClassifier(max_depth=2)
base_model_2 = DecisionTreeClassifier(max_depth=2)
base_model_3 = DecisionTreeClassifier(max_depth=2)

In [9]:
base_model_1

DecisionTreeClassifier(max_depth=2)

In [10]:
sample_1.iloc[:,:30]

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
473        12.27         29.97           77.42      465.4          0.07699   
307         9.00         14.40           56.36      246.3          0.07005   
6          18.25         19.98          119.60     1040.0          0.09463   
284        12.89         15.70           84.08      516.6          0.07818   
10         16.02         23.24          102.70      797.8          0.08206   
..           ...           ...             ...        ...              ...   
350        11.66         17.07           73.70      421.0          0.07561   
60         10.17         14.88           64.55      311.9          0.11340   
465        13.24         20.13           86.87      542.9          0.08284   
124        13.37         16.39           86.10      553.5          0.07115   
13         15.85         23.95          103.70      782.7          0.08401   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
473           0.03398        0.000000             0.000000         0.1701   
307           0.03116        0.003681             0.003472         0.1788   
6             0.10900        0.112700             0.074000         0.1794   
284           0.09580        0.111500             0.033900         0.1432   
10            0.06669        0.032990             0.033230         0.1528   
..                ...             ...                  ...            ...   
350           0.03630        0.008306             0.011620         0.1671   
60            0.08061        0.010840             0.012900         0.2743   
465           0.12230        0.101000             0.028330         0.1601   
124           0.07325        0.080920             0.028000         0.1422   
13            0.10020        0.099380             0.053640         0.1847   

     mean fractal dimension  ...  worst radius  worst texture  \
473                 0.05960  ...        13.450          38.05   
307                 0.06833  ...         9.699          20.07   
6                   0.05742  ...        22.880          27.66   
284                 0.05935  ...        13.900          19.69   
10                  0.05697  ...        19.190          33.88   
..                      ...  ...           ...            ...   
350                 0.05731  ...        13.280          19.74   
60                  0.06960  ...        11.020          17.45   
465                 0.06432  ...        15.440          25.50   
124                 0.05823  ...        14.260          22.75   
13                  0.05338  ...        16.840          27.66   

     worst perimeter  worst area  worst smoothness  worst compactness  \
473            85.08       558.9           0.09422            0.05213   
307            60.90       285.5           0.09861            0.05232   
6             153.20      1606.0           0.14420            0.25760   
284            92.12       595.6           0.09926            0.23170   
10            123.80      1150.0           0.11810            0.15510   
..               ...         ...               ...                ...   
350            83.61       542.5           0.09958            0.06476   
60             69.86       368.6           0.12750            0.09866   
465           115.00       733.5           0.12010            0.56460   
124            91.99       632.1           0.10250            0.25310   
13            112.00       876.5           0.11310            0.19240   

     worst concavity  worst concave points  worst symmetry  \
473          0.00000               0.00000          0.2409   
307          0.01472               0.01389          0.2991   
6            0.37840               0.19320          0.3063   
284          0.33440               0.10170          0.1999   
10           0.14590               0.09975          0.2948   
..               ...                   ...             ...   
350          0.03046               0.04262         

In [11]:
base_model_1.fit(sample_1.iloc[:,:30],sample_1.iloc[:,-1])
base_model_2.fit(sample_2.iloc[:,:30],sample_2.iloc[:,-1])
base_model_3.fit(sample_3.iloc[:,:30],sample_3.iloc[:,-1])

DecisionTreeClassifier(max_depth=2)

In [12]:
for i in df.sample():
    print(i)

mean radius
mean texture
mean perimeter
mean area
mean smoothness
mean compactness
mean concavity
mean concave points
mean symmetry
mean fractal dimension
radius error
texture error
perimeter error
area error
smoothness error
compactness error
concavity error
concave points error
symmetry error
fractal dimension error
worst radius
worst texture
worst perimeter
worst area
worst smoothness
worst compactness
worst concavity
worst concave points
worst symmetry
worst fractal dimension
target


In [13]:
df.sample().values

array([[1.462e+01, 2.402e+01, 9.457e+01, 6.627e+02, 8.974e-02, 8.606e-02,
        3.102e-02, 2.957e-02, 1.685e-01, 5.866e-02, 3.721e-01, 1.111e+00,
        2.279e+00, 3.376e+01, 4.868e-03, 1.818e-02, 1.121e-02, 8.606e-03,
        2.085e-02, 2.893e-03, 1.611e+01, 2.911e+01, 1.029e+02, 8.037e+02,
        1.115e-01, 1.766e-01, 9.189e-02, 6.946e-02, 2.522e-01, 7.246e-02,
        1.000e+00]])

In [14]:
df.drop(df['target'].values)

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
5          12.45         15.70           82.57      477.1          0.12780   
6          18.25         19.98          119.60     1040.0          0.09463   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
5             0.17000         0.15780              0.08089         0.2087   
6             0.10900         0.11270              0.07400         0.1794   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
2                   0.05999  ...          25.53           152.50      1709.0   
3                   0.09744  ...          26.50            98.87       567.7   
4                   0.05883  ...          16.67           152.20      1575.0   
5                   0.07613  ...          23.75           103.40       741.6   
6                   0.05742  ...          27.66           153.20      1606.0   
..                      ...  ...            ...              ...         ...   
564                 0.05623  ...          26.40           166.10      2027.0   
565                 0.05533  ...          38.25           155.00      1731.0   
566                 0.05648  ...          34.12           126.70      1124.0   
567                 0.07016  ...          39.42           184.60      1821.0   
568                 0.05884  ...          30.37            59.16       268.6   

     worst smoothness  worst compactness  worst concavity  \
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
5             0.17910            0.52490           0.5355   
6             0.14420            0.25760           0.3784   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     worst concave points  worst symmetry  worst fractal dimension  target  
2                  0.2430          0.3613                  0.08758       0  
3                  0.2575          0.6638                  0.17300       0  
4                  0.1625          0.2364                  0.07678       0  
5                  0.1741          0.3985                  0.12440       0  
6                  0.1932          0.3063                  0.083

In [15]:
sample_ = df.iloc[:,:30].sample(1).values
sample_

array([[1.133e+01, 1.416e+01, 7.179e+01, 3.966e+02, 9.379e-02, 3.872e-02,
        1.487e-03, 3.333e-03, 1.954e-01, 5.821e-02, 2.375e-01, 1.280e+00,
        1.565e+00, 1.709e+01, 8.426e-03, 8.998e-03, 1.487e-03, 3.333e-03,
        2.358e-02, 1.627e-03, 1.220e+01, 1.899e+01, 7.737e+01, 4.580e+02,
        1.259e-01, 7.348e-02, 4.955e-03, 1.111e-02, 2.758e-01, 6.386e-02]])

In [16]:
#base_model_1.predict(df.iloc[:,:30].sample(1).values)

In [17]:
model1 = base_model_1.predict(sample_)
model1

array([1])

In [18]:
model2 = base_model_2.predict(sample_)
model2

array([1])

In [19]:
model3 = base_model_3.predict(sample_)
model3

array([1])

In [20]:
predicted_op = np.concatenate((model1, model2, model3))
predicted_op

array([1, 1, 1])

In [21]:
from statistics import mode, mean
output_mode = mode(predicted_op)
output_mean = mean(predicted_op)

In [22]:
output_mean

1

In [23]:
output_mode

1