In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = load_breast_cancer()

In [3]:
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target

df.sample(4)

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
396        13.51         18.89           88.10      558.1          0.10590   
312        12.76         13.37           82.29      504.1          0.08794   
426        10.48         14.98           67.49      333.6          0.09816   
201        17.54         19.32          115.10      951.6          0.08968   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
396           0.11470         0.08580              0.05381         0.1806   
312           0.07948         0.04052              0.02548         0.1601   
426           0.10130         0.06335              0.02218         0.1925   
201           0.11980         0.10360              0.07488         0.1506   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
396                 0.06079  ...          27.20            97.33       675.2   
312                 0.06140  ...          16.40            92.04       618.8   
426                 0.06915  ...          21.57            81.41       440.4   
201                 0.05491  ...          25.84           139.50      1239.0   

     worst smoothness  worst compactness  worst concavity  \
396            0.1428             0.2570           0.3438   
312            0.1194             0.2208           0.1769   
426            0.1327             0.2996           0.2939   
201            0.1381             0.3420           0.3508   

     worst concave points  worst symmetry  worst fractal dimension  target  
396               0.14530          0.2666                  0.07686       1  
312               0.08411          0.2564                  0.08253       1  
426               0.09310          0.3020                  0.09646       1  
201               0.19390          0.2928                  0.07867       0  

[4 rows x 31 columns]

In [4]:
df.shape

(569, 31)

In [5]:
sample_1 = df.sample(200, replace = True)
sample_2 = df.sample(200, replace = True)
sample_3 = df.sample(200, replace = True)

In [6]:
sample_1.shape

(200, 31)

In [7]:
from sklearn.tree import DecisionTreeClassifier

In [8]:
base_model_1 = DecisionTreeClassifier(max_depth=2)
base_model_2 = DecisionTreeClassifier(max_depth=2)
base_model_3 = DecisionTreeClassifier(max_depth=2)

In [9]:
base_model_1

DecisionTreeClassifier(max_depth=2)

In [10]:
sample_1.iloc[:,:30]

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
242        11.30         18.19           73.93      389.4          0.09592   
428        11.13         16.62           70.47      381.1          0.08151   
302        20.09         23.86          134.70     1247.0          0.10800   
81         13.34         15.86           86.49      520.0          0.10780   
296        10.91         12.35           69.14      363.7          0.08518   
..           ...           ...             ...        ...              ...   
286        11.94         20.76           77.87      441.0          0.08605   
276        11.33         14.16           71.79      396.6          0.09379   
349        11.95         14.96           77.23      426.7          0.11580   
193        12.34         26.86           81.15      477.4          0.10340   
156        17.68         20.74          117.40      963.7          0.11150   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
242           0.13250        0.154800             0.028540         0.2054   
428           0.03834        0.013690             0.013700         0.1511   
302           0.18380        0.228300             0.128000         0.2249   
81            0.15350        0.116900             0.069870         0.1942   
296           0.04721        0.012360             0.013690         0.1449   
..                ...             ...                  ...            ...   
286           0.10110        0.065740             0.037910         0.1588   
276           0.03872        0.001487             0.003333         0.1954   
349           0.12060        0.011710             0.017870         0.2459   
193           0.13530        0.108500             0.045620         0.1943   
156           0.16650        0.185500             0.105400         0.1971   

     mean fractal dimension  ...  worst radius  worst texture  \
242                 0.07669  ...         12.58          27.96   
428                 0.06148  ...         11.68          20.29   
302                 0.07469  ...         23.68          29.43   
81                  0.06902  ...         15.53          23.19   
296                 0.06031  ...         11.37          14.82   
..                      ...  ...           ...            ...   
286                 0.06766  ...         13.24          27.29   
276                 0.05821  ...         12.20          18.99   
349                 0.06581  ...         12.81          17.72   
193                 0.06937  ...         15.65          39.34   
156                 0.06166  ...         20.47          25.11   

     worst perimeter  worst area  worst smoothness  worst compactness  \
242            87.16       472.9           0.13470            0.48480   
428            74.35       421.1           0.10300            0.06219   
302           158.80      1696.0           0.13470            0.33910   
81             96.66       614.9           0.15360            0.47910   
296            72.42       392.2           0.09312            0.07506   
..               ...         ...               ...                ...   
286            92.20       546.1           0.11160            0.28130   
276            77.37       458.0           0.12590            0.07348   
349            83.09       496.2           0.12930            0.18850   
193           101.70       768.9           0.17850            0.47060   
156           132.90      1302.0           0.14180            0.34980   

     worst concavity  worst concave points  worst symmetry  \
242         0.743600               0.12180          0.3308   
428         0.045800               0.04044          0.2383   
302         0.493200               0.19230          0.3294   
81          0.485800               0.17080          0.3527   
296         0.028840               0.03194          0.2143   
..               ...                   ...             ...   
286         0.236500               0.11550         

In [11]:
base_model_1.fit(sample_1.iloc[:,:30],sample_1.iloc[:,-1])
base_model_2.fit(sample_2.iloc[:,:30],sample_2.iloc[:,-1])
base_model_3.fit(sample_3.iloc[:,:30],sample_3.iloc[:,-1])

DecisionTreeClassifier(max_depth=2)

In [12]:
for i in df.sample():
    print(i)

mean radius
mean texture
mean perimeter
mean area
mean smoothness
mean compactness
mean concavity
mean concave points
mean symmetry
mean fractal dimension
radius error
texture error
perimeter error
area error
smoothness error
compactness error
concavity error
concave points error
symmetry error
fractal dimension error
worst radius
worst texture
worst perimeter
worst area
worst smoothness
worst compactness
worst concavity
worst concave points
worst symmetry
worst fractal dimension
target


In [13]:
df.sample().values

array([[1.018e+01, 1.753e+01, 6.512e+01, 3.131e+02, 1.061e-01, 8.502e-02,
        1.768e-02, 1.915e-02, 1.910e-01, 6.908e-02, 2.467e-01, 1.217e+00,
        1.641e+00, 1.505e+01, 7.899e-03, 1.400e-02, 8.534e-03, 7.624e-03,
        2.637e-02, 3.761e-03, 1.117e+01, 2.284e+01, 7.194e+01, 3.756e+02,
        1.406e-01, 1.440e-01, 6.572e-02, 5.575e-02, 3.055e-01, 8.797e-02,
        1.000e+00]])

In [14]:
df.drop(df['target'].values)

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
5          12.45         15.70           82.57      477.1          0.12780   
6          18.25         19.98          119.60     1040.0          0.09463   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
5             0.17000         0.15780              0.08089         0.2087   
6             0.10900         0.11270              0.07400         0.1794   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
2                   0.05999  ...          25.53           152.50      1709.0   
3                   0.09744  ...          26.50            98.87       567.7   
4                   0.05883  ...          16.67           152.20      1575.0   
5                   0.07613  ...          23.75           103.40       741.6   
6                   0.05742  ...          27.66           153.20      1606.0   
..                      ...  ...            ...              ...         ...   
564                 0.05623  ...          26.40           166.10      2027.0   
565                 0.05533  ...          38.25           155.00      1731.0   
566                 0.05648  ...          34.12           126.70      1124.0   
567                 0.07016  ...          39.42           184.60      1821.0   
568                 0.05884  ...          30.37            59.16       268.6   

     worst smoothness  worst compactness  worst concavity  \
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
5             0.17910            0.52490           0.5355   
6             0.14420            0.25760           0.3784   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     worst concave points  worst symmetry  worst fractal dimension  target  
2                  0.2430          0.3613                  0.08758       0  
3                  0.2575          0.6638                  0.17300       0  
4                  0.1625          0.2364                  0.07678       0  
5                  0.1741          0.3985                  0.12440       0  
6                  0.1932          0.3063                  0.083

In [15]:
sample_ = df.iloc[:,:30].sample(1).values

In [16]:
#base_model_1.predict(df.iloc[:,:30].sample(1).values)

In [17]:
base_model_1.predict(sample_)

array([0])

In [18]:
base_model_2.predict(sample_)

array([0])

In [19]:
base_model_3.predict(sample_)

array([0])